# SPDX-License-Identifier: MPL-2.0
name: Elixir CI
on: [push, pull_request]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          otp-version: '26'
          elixir-version: '1.15'
      
      - name: Cache deps
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: deps
          key: deps-${{ hashFiles('mix.lock') }}
      
      - name: Install deps
        run: mix deps.get
      
      - name: Compile
        run: mix compile --warnings-as-errors
      
      - name: Credo lint
        run: mix credo --strict
      
      - name: Dialyzer
        run: mix dialyzer
      
      - name: Run tests
        run: mix test --cover
      
      - name: Security check
        run: mix deps.audit || true
